const FLAVOR_TEXT = [
    '',
    'Rotating sideways',
    'Turning into a duck',
    'Finding out nothing',
    'Laughing maniacally',
    'Destroying cities',
    'Passwording',
    'Removing artificial additives',
    'Spicing things up',
    'Reaching you about your car\'s extended warranty',
    'Look behind you',
    'Crawling over imaginary tunnels',
    'Inflating stuffed animals',
    'Securing your password',
    'Running code',
    'Discovering long-lost relatives',
    'AMOGUS',
    'It\'s about drive, it\'s about power',
    'Putting together puzzles',
    'Turning the world upside down',
    'Smashing keyboards',
    'Finding alternate realities',
    'Rocks',
    'Consuming too much',
    'Managing time',
    'Waiting for nothing',
    'Taking a break',
    'Waiting for someone',
    'Doing absolutely nothing',
    'Slurping Slurpees',
    'Uncovering gold',
    'Exploring alternate dimensions',
    'DEATH',
    'Weeding out the weeds',
    'Controlling pests',
    'Chomping down pizza',
    'Enjoy life while you can',
    'Wow',
    'Touching others\' stuff',
    'Digesting food',
    'Tracking animal prints',
    'Exercising snakes',
    'Discovering unicorns',
    'Watching you read',
    'Magically formulation-inating',
    'Doing secret stuff',
    'Creating nothing',
    'Rage quitting',
    'Cringing at memes',
    'Hacking hackers',
    'Creating country \'Travania\'',
    'Asking why',
    'Doing your homework',
    'Doing advanced stuff',
    'Crawling overzealously',
    'Dispersing of thy throughout',
    'Bo\'o \'o wo\'o (bottle of water in British)',
    'Biting fingernails',
    'Causing chaos',
    'Waiting nervously',
    'Knocking on wood',
    'Smashing mirrors',
    'Cutting through earth',
    'Wondering about stuff',
    'Chewing gum in class',
    'Abducting aliens',
    'Mashing keyboard, creating password',
    'Generating Super Ultra Secureness',
    'Doing nothing harmful at all',
    'Why',
    'Yes, it is',
    'That isn\'t',
    'Becoming bilingual',
    'Discovering opportuninties',
    'Cracking knuckles',
    'Turtling hoods',
    'Becoming carbon neutral',
    'Activating Chaos Management System (CMS)',
    'Looking in awe',
    'You look nice today',
    'How did you even',
    'Lifting weights',
    'Snoring obnoxiously',
    'Not gaslighting people',
    'Getting sleepier',
    'Smashing out horrible music',
    'Singing terribly',
    'Doing math homework',
    'Studying for midterms',
    'Reading books',
    'Asking nicely',
    'Take a screen break',
    'Running marathons',
    'Signing legal documents',
    'Dreaming about ponies and rainbows',
    'Picking daisies',
    'Snapping back to reality',
    'Dreaming wonderfully',
    'Repairing stuff',
    'Fixing what\'s not broken',
    'Crying to sleep',
    'Becoming nostalgic',
    'Suspicious rainbow donkeys spat',
    'Happy belated birthday',
    'Here\'s an early happy birthday',
    'Stay hydrated',
    'Unchecking checked unchecked-boxes',
    'Taking up more RAM',
    'Hogging system resources',
    'Becoming 32% more sarcastic',
    'Rotating 43.2 degrees',
    'Psuedo-randomizing',
    'Watching you wait',
    'Completing online surveys',
    'Not going to sketchy sites',
    'Switching seasons',
    'Teleporting to places',
    'Waving magic wands',
    'Teleporting to fantasy lands',
    'Paying taxes',
    'Acing tests',
    'Riding metros',
    'Flying planes',
    'Unpolluting skies',
    'Eating messily',
    'Charging devices',
    'Doing cartwheels',
    'Performing operas',
    'Creating epic beats',
    'Installing wind turbines',
    'Gossiping',
    'Writing an essay',
    'Gaining hope',
    'Going to bed',
    'You may not sleep right now, there are monsters nearby',
    'Vibing to music',
    'Gaining social credits',
    'Slamming doors shut',
    'Giving lectures',
    'Swimming at the beach',
    'Being patriotic',
    'Taking off in 2.3 seconds',
    'Get the COVID vaccine',
    'Running on treadmills',
    'Going shopping for plates',
    'Painting paintings',
    'Collapsing under pressure',
    'Lotionizing skin',
    'Cloning clones of clones',
    'Delivering mail',
    'Blinking furiously',
    'Achieving achievements',
    'Memorizing books',
    'Creating corny jokes',
    'Nodding enthusiastically',
    'Washing clothes',
    'Social distancing',
    'Providing evidence',
    'Singing anthems',
    'Makking in China',
    'Shredding confidential documents',
    'Watching paint dry',
    'Giving pop quizzes',
    'Using Wikipedia as a source',
    'Rickrolling',
    'Acting out plays',
    'Telling spooky stories',
    'Marketing products',
    'Just stretching',
    'Evaporating water',
    'Unscrewing lids',
    'Navigating catalogs',
    'Impressing others',
    'Raising money',
    'Applying for jobs',
    'Watching clocks tick',
    'Overexaggerating',
    'Turning on fans',
    'Landing paper into trash bins',
    'Organizing papers',
    'Becoming speechless',
    'No comment',
    'Adding together numbers',
    'Creating nonsensical phrases',
    'Asking questions',
    'Filtering out bad air',
    'Twisting door handles',
    'Riding bikes',
    'Unlocking locked locks',
    'Replacing light bulbs',
    'Going to birthday parties',
    'Breaking world records',
    'Living on the edge',
    'Opening all the drawers',
    'Changing time zones',
    'Avoiding chaos',
    'Peeling cheese sticks',
    'Watering plants'
];
